site_name: DF No Ponto
docs_dir: ./docs
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences 
  - tables

plugins:
  - search

theme:
  name: material
  logo: assets/logos/logo_small.png
  favicon: assets/logos/logo_small.png
  font:
    text: Open Sans
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: custom

extra_css:
  - assets/stylesheets/extra.css

repo_url: https://github.com/Requisitos-de-Software/2025.2-Grupo06
repo_name: "2025.2-Grupo06"

nav:
  - Início: index.md
  - Artefatos:
      - "Etapa 1: Planejamento do Projeto e Pré-Rastreabilidade":
          - Apresentação: Apresentação/apresentacao01.md
          - Planejamento do Projeto:
              - Sobre o aplicativo escolhido: Planejamento/Aplicativoescolhido.md
              - Ferramentas utilizadas: Planejamento/Ferramentasuti.md
              - Cronograma detalhado: Planejamento/Cronogramadetalhado.md
              - Heatmap de disponibilidde: Planejamento/Heatmap.md
          - Pré-Rastreabilidade:
              - Rich Picture: pre-rastreabilidade/rich_picture.md
          - Lista de Verificação: checklist/lista01.md
          - Tabela de Contribuição: Contribuições/tab_cont01.md

      - "Etapa 2: Elicitação - Técnicas e Priorização de Requisitos":
          - Apresentação: Apresentação/apresentacao02.md
          - Perfil de Usuário:
              - Perfil: Elicitacao/perfil.md
              - Personas: Elicitacao/perfil_personas.md
              - Cenários: Elicitacao/perfil_cenarios.md
          - Elicitação de Requisitos:
              - Tabela Geral de Requisitos Elicitados: Elicitacao/elicitacao_lista_requisitos_elicitados.md
              - Técnicas de Elicitação de Requisitos:
                  - Análise de Documentos: Elicitacao/elicitacao_analise_documentos.md
                  - Entrevista: Elicitacao/elicitacao_entrevista.md
                  - Brainstorm: Elicitacao/elicitacao_brainstorm.md
          - Técnicas de Priorização de Requisitos:
              - $100: Elicitacao/priorizacao_100_dollars.md
              - In or Out: Elicitacao/priorizacao_in_or_out.md
              - First Things First: Elicitacao/priorizacao_first_things_first.md
              - MoSCow: Elicitacao/priorizacao_moscow.md
          - Lista de Verificação: checklist/lista02.md
          - Tabela de Contribuição: Contribuições/tab_cont02.md

      - "Etapa 3: Modelagem de Requisitos 1":
          - Apresentação: Apresentação/apresentacao03.md
          - Cenários: modelagem_requisitos_01/cenarios.md
          - Léxicos: modelagem_requisitos_01/lexicos.md
          - Casos de Uso: modelagem_requisitos_01/casos_de_uso.md
          - Especificação Suplementar: modelagem_requisitos_01/especificacao_suplementar.md
          - Lista de Verificação: checklist/lista03.md
          - Tabela de Contribuição: Contribuições/tab_cont03.md

      - "Etapa 4: Modelagem de Requisitos 2 (Ágil)":
          - Apresentação: Apresentação/apresentacao04.md
          - Histórias de Usuário: modelagem_requisitos_02/historias_de_usuario.md
          - Backlog: modelagem_requisitos_02/backlog.md
          - NFR Framework: modelagem_requisitos_02/nfr.md
          - Lista de Verificação: checklist/lista04.md
          - Tabela de Contribuição: Contribuições/tab_cont04.md

      - "Etapa 5: Análise de Requisitos - Verificação e Validação":
          - Apresentação: Apresentação/apresentacao06.md
          - Verificação de Requisitos: validacao_verificacao/verificacao.md
          - Validação de Requisitos:
              - Prototipação: validacao_verificacao/prototipacao.md
              - Comprovação Informal: validacao_verificacao/comprovacao.md
          - Tabela de Contribuição: Contribuições/tab_cont06.md

      - "Etapa 6: Pós-rastreabilidade":
          - Apresentação: Apresentação/apresentacao05.md
          - Backward-from: pos-rastreabilidade/backward.md
          - Forward-from: pos-rastreabilidade/forward.md
          - Matriz de Pós-rastreabilidade: pos-rastreabilidade/matriz.md
          - Lista de Verificação: checklist/lista05.md
          - Tabela de Contribuição: Contribuições/tab_cont05.md

  - Atas de Reunião:
      - Ata 1 - 04/09: Atas de Reunião/ata1.md
      - Ata 2 - 05/09: Atas de Reunião/ata2.md
      - Ata 3 - 07/09: Atas de Reunião/ata3.md
      - Ata 4 - 22/09: Atas de Reunião/ata4.md
      - Ata 5 - 28/09: Atas de Reunião/ata5.md

  - Verificações:
      - Inspeções do Grupo 6 (Monitores):
          - "Etapa 1": Verificações/inspecoes_grupo_6/inspecao01.md
          - "Etapa 2": Verificações/inspecoes_grupo_6/inspecao02.md
          - "Etapa 3": Verificações/inspecoes_grupo_6/inspecao03.md
      - Inspeções do Grupo 7:
          - "Etapa 1": Verificações/inspecao01.md
          - "Etapa 2": Verificações/inspecao02.md
          - "Etapa 3": Verificações/inspecao03.md
          - "Etapa 4": Verificações/inspecao04.md
          - "Etapa 6": Verificações/inspecao05.md
